[versions]
androidxActivity = "1.3.0-beta01"
androidxAppcompat = "1.3.0"
androidxCore = "1.5.0"
androidxEspresso = "3.3.0"
androidxLifecycle = "2.3.1"
androidxTest = "1.1.2"
compose = "1.0.0-beta08"
junit4 = "4.13.2"

[libraries]
androidx-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
androidx-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-compose-uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-test = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTest" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
