name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11
        sdk:
          - 21
          - 30
          - 31

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: v1-${{ runner.os }}-gradle-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            v1-${{ runner.os }}-gradle-${{ matrix.java-version }}-

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Create robolectric.properties
        run: |
          mkdir app/src/sharedTest/resources/com/alexvanyo/composelife
          echo sdk=${{ matrix.sdk }} > app/src/sharedTest/resources/com/alexvanyo/composelife/robolectric.properties

      - name: Run checks
        run: ./gradlew check --stacktrace

  android-test:
    needs: build
    runs-on: macos-latest # for hardware acceleration

    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 11

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle Files
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: v1-${{ runner.os }}-gradle-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            v1-${{ runner.os }}-gradle-${{ matrix.java-version }}-

      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Run device checks
        run: ./gradlew pixel2api29Check --stacktrace
